# Generated by Django 4.2.2 on 2023-06-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
