# Generated by Django 4.1.5 on 2023-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_authentication', '0005_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
