# Generated by Django 4.1.5 on 2023-12-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_authentication', '0006_userprofile_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
