POST http://127.0.0.1:8000/api/v1/post/create-post/
Content-Type: application/json
Authorization: Token fc6cc1fc09c68ab00af9eb1cd97475630f1887ad

{
    "title":"title test",
    "description":"description test",
    "author": 1
}



###
DELETE http://127.0.0.1:8000/api/v1/post/delete-post/3/
Content-Type: application/json
Authorization: Token fc6cc1fc09c68ab00af9eb1cd97475630f1887ad

# {
#     "title":"title test",
#     "description":"description test",
#     "author": 1
# }