POST http://127.0.0.1:8000/api/v1/post/create-post/
Content-Type: application/json
Authorization: Token 05fc89e52bb622aa7474b0a7ce934d9acc4d02f7

{
    "title":"user id (3)",
    "description":"stay",
    "author": 3
}

# 29cfbfa761165604f050ce293109f4cf5f2eee9d
# ec34af96eb5baa3a17676b586b92bf300f6c6194
# 05fc89e52bb622aa7474b0a7ce934d9acc4d02f7
###
DELETE http://127.0.0.1:8000/api/v1/post/delete-post/5/
Content-Type: application/json
Authorization: Token 0de67b963b3bdd76422d2dcbe9c518d85f97b2ff

# {
#     "title":"title test",
#     "description":"description test",
#     "author": 1
# }