POST http://127.0.0.1:8000/api/v1/auth/login/
Content-Type: application/json

{}


####


POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "username": "omar1",
    "password": "omar123",
    "email": "omar123@gevox.com"
}


####
POST http://127.0.0.1:8000/api/v1/auth/delete-user/
Content-Type: application/json

{
    "username": "omar1",
    "password": "omar123",
    "email": "omar123@gevox.com"
}

