# Generated by Django 4.2.2 on 2023-06-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sparks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spark', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='postmodel',
            name='spark',
            field=models.ManyToManyField(to='gevox_posts.sparks'),
        ),
    ]
