# Generated by Django 4.2.2 on 2023-06-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_posts', '0002_sparks_postmodel_spark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparks',
            old_name='spark',
            new_name='sparks',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='spark',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='sparks',
            field=models.ManyToManyField(to='gevox_posts.sparks'),
        ),
    ]
