# Generated by Django 4.2.2 on 2023-06-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_posts', '0003_postmodel_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
