# Generated by Django 4.2.2 on 2023-07-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_posts', '0004_postmodel_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparks',
            old_name='sparks',
            new_name='spark',
        ),
    ]
