# Generated by Django 4.2.2 on 2023-07-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_posts', '0005_rename_sparks_sparks_spark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparks',
            old_name='spark',
            new_name='sparks',
        ),
    ]
