# Generated by Django 4.1.5 on 2023-12-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_posts', '0007_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gevox_posts.postmodel'),
        ),
    ]
