# Generated by Django 4.1.5 on 2023-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevox_posts', '0008_rename_createdat_postmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
